parameters:
    lock.shortlink_ttl: '%env(float:LOCK_SHORTLINK_TTL)%'
    service.base_url: '%env(string:BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            float $ttl: '%lock.shortlink_ttl%'
            string $baseUrl: '%service.base_url%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

        ## --------------- ##
        ##    Services     ##
        ## --------------- ##

    app.services.shortlink_service:
        class: App\Service\ShortLinkService
        autowire: true
        public: true
        arguments:
            $baseUrl: '%service.base_url%'

    app.lock.shortlink_lock_factory:
        class: App\Lock\ShortLinkLockFactory
        autowire: true
        public: true
        arguments:
            $lockFactory: '@lock.factory'
            $ttl: '%lock.shortlink_ttl%'
